-- CREATE TABLE IF NOT EXISTS AccTransaction(
--         id bigint ,
--         accountNumber char(20),
--         type char(20),
--         accountFrom char (20),
--         currency char (20),
--         amount char (20),
--         PRIMARY KEY(`id`)
-- );